// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.14.0
// source: quant-order.proto

package pub

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateGridOrderReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid int64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	// 券商类型 1模拟交易
	BrokerType int32 `protobuf:"varint,2,opt,name=broker_type,json=brokerType,proto3" json:"broker_type,omitempty"`
	// 量化类型 1网格交易
	QuantType int32 `protobuf:"varint,3,opt,name=quant_type,json=quantType,proto3" json:"quant_type,omitempty"`
	// 资产类型 1上证 2深证 3美股(包括道琼斯和纳斯达克) 4港股
	AssetType int32 `protobuf:"varint,4,opt,name=asset_type,json=assetType,proto3" json:"asset_type,omitempty"`
	// 资产代号
	AssetCode string `protobuf:"bytes,5,opt,name=asset_code,json=assetCode,proto3" json:"asset_code,omitempty"`
	// 投入资金量 全都*1000,转为整数
	TotalMoney int64 `protobuf:"varint,6,opt,name=total_money,json=totalMoney,proto3" json:"total_money,omitempty"`
	// 网格数量
	GridNum int64 `protobuf:"varint,7,opt,name=grid_num,json=gridNum,proto3" json:"grid_num,omitempty"`
	// 网格上限
	GridMax int64 `protobuf:"varint,8,opt,name=grid_max,json=gridMax,proto3" json:"grid_max,omitempty"`
	// 网格下限
	GridMin int64 `protobuf:"varint,9,opt,name=grid_min,json=gridMin,proto3" json:"grid_min,omitempty"`
}

func (x *CreateGridOrderReq) Reset() {
	*x = CreateGridOrderReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quant_order_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGridOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGridOrderReq) ProtoMessage() {}

func (x *CreateGridOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_quant_order_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGridOrderReq.ProtoReflect.Descriptor instead.
func (*CreateGridOrderReq) Descriptor() ([]byte, []int) {
	return file_quant_order_proto_rawDescGZIP(), []int{0}
}

func (x *CreateGridOrderReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *CreateGridOrderReq) GetBrokerType() int32 {
	if x != nil {
		return x.BrokerType
	}
	return 0
}

func (x *CreateGridOrderReq) GetQuantType() int32 {
	if x != nil {
		return x.QuantType
	}
	return 0
}

func (x *CreateGridOrderReq) GetAssetType() int32 {
	if x != nil {
		return x.AssetType
	}
	return 0
}

func (x *CreateGridOrderReq) GetAssetCode() string {
	if x != nil {
		return x.AssetCode
	}
	return ""
}

func (x *CreateGridOrderReq) GetTotalMoney() int64 {
	if x != nil {
		return x.TotalMoney
	}
	return 0
}

func (x *CreateGridOrderReq) GetGridNum() int64 {
	if x != nil {
		return x.GridNum
	}
	return 0
}

func (x *CreateGridOrderReq) GetGridMax() int64 {
	if x != nil {
		return x.GridMax
	}
	return 0
}

func (x *CreateGridOrderReq) GetGridMin() int64 {
	if x != nil {
		return x.GridMin
	}
	return 0
}

type CreateGridOrderRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 投入资金量
	TotalMoney int64 `protobuf:"varint,1,opt,name=total_money,json=totalMoney,proto3" json:"total_money,omitempty"`
	// 网格详情
	Grids []*GridData `protobuf:"bytes,2,rep,name=grids,proto3" json:"grids,omitempty"`
}

func (x *CreateGridOrderRes) Reset() {
	*x = CreateGridOrderRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quant_order_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGridOrderRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGridOrderRes) ProtoMessage() {}

func (x *CreateGridOrderRes) ProtoReflect() protoreflect.Message {
	mi := &file_quant_order_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGridOrderRes.ProtoReflect.Descriptor instead.
func (*CreateGridOrderRes) Descriptor() ([]byte, []int) {
	return file_quant_order_proto_rawDescGZIP(), []int{1}
}

func (x *CreateGridOrderRes) GetTotalMoney() int64 {
	if x != nil {
		return x.TotalMoney
	}
	return 0
}

func (x *CreateGridOrderRes) GetGrids() []*GridData {
	if x != nil {
		return x.Grids
	}
	return nil
}

type GridData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 资产数
	AssetNum int64 `protobuf:"varint,1,opt,name=asset_num,json=assetNum,proto3" json:"asset_num,omitempty"`
	// 上线
	GridMax int64 `protobuf:"varint,2,opt,name=grid_max,json=gridMax,proto3" json:"grid_max,omitempty"`
	// 下线
	GridMin int64 `protobuf:"varint,3,opt,name=grid_min,json=gridMin,proto3" json:"grid_min,omitempty"`
}

func (x *GridData) Reset() {
	*x = GridData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quant_order_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GridData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GridData) ProtoMessage() {}

func (x *GridData) ProtoReflect() protoreflect.Message {
	mi := &file_quant_order_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GridData.ProtoReflect.Descriptor instead.
func (*GridData) Descriptor() ([]byte, []int) {
	return file_quant_order_proto_rawDescGZIP(), []int{2}
}

func (x *GridData) GetAssetNum() int64 {
	if x != nil {
		return x.AssetNum
	}
	return 0
}

func (x *GridData) GetGridMax() int64 {
	if x != nil {
		return x.GridMax
	}
	return 0
}

func (x *GridData) GetGridMin() int64 {
	if x != nil {
		return x.GridMin
	}
	return 0
}

type Asset struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 资产类型 -1人名币 -2港币 -3美元 1上证 2深证 3美股(包括道琼斯和纳斯达克) 4港股
	AssetType int32  `protobuf:"varint,1,opt,name=asset_type,json=assetType,proto3" json:"asset_type,omitempty"`
	AssetCode string `protobuf:"bytes,2,opt,name=asset_code,json=assetCode,proto3" json:"asset_code,omitempty"`
	AssetNum  int64  `protobuf:"varint,3,opt,name=asset_num,json=assetNum,proto3" json:"asset_num,omitempty"`
}

func (x *Asset) Reset() {
	*x = Asset{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quant_order_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Asset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Asset) ProtoMessage() {}

func (x *Asset) ProtoReflect() protoreflect.Message {
	mi := &file_quant_order_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Asset.ProtoReflect.Descriptor instead.
func (*Asset) Descriptor() ([]byte, []int) {
	return file_quant_order_proto_rawDescGZIP(), []int{3}
}

func (x *Asset) GetAssetType() int32 {
	if x != nil {
		return x.AssetType
	}
	return 0
}

func (x *Asset) GetAssetCode() string {
	if x != nil {
		return x.AssetCode
	}
	return ""
}

func (x *Asset) GetAssetNum() int64 {
	if x != nil {
		return x.AssetNum
	}
	return 0
}

type CloseOrderReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid int64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Oid int64 `protobuf:"varint,2,opt,name=oid,proto3" json:"oid,omitempty"`
}

func (x *CloseOrderReq) Reset() {
	*x = CloseOrderReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quant_order_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CloseOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseOrderReq) ProtoMessage() {}

func (x *CloseOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_quant_order_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseOrderReq.ProtoReflect.Descriptor instead.
func (*CloseOrderReq) Descriptor() ([]byte, []int) {
	return file_quant_order_proto_rawDescGZIP(), []int{4}
}

func (x *CloseOrderReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *CloseOrderReq) GetOid() int64 {
	if x != nil {
		return x.Oid
	}
	return 0
}

type CloseOrderRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CloseOrderRes) Reset() {
	*x = CloseOrderRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quant_order_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CloseOrderRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseOrderRes) ProtoMessage() {}

func (x *CloseOrderRes) ProtoReflect() protoreflect.Message {
	mi := &file_quant_order_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseOrderRes.ProtoReflect.Descriptor instead.
func (*CloseOrderRes) Descriptor() ([]byte, []int) {
	return file_quant_order_proto_rawDescGZIP(), []int{5}
}

type GetOrdersByUidReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid int64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *GetOrdersByUidReq) Reset() {
	*x = GetOrdersByUidReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quant_order_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOrdersByUidReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrdersByUidReq) ProtoMessage() {}

func (x *GetOrdersByUidReq) ProtoReflect() protoreflect.Message {
	mi := &file_quant_order_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrdersByUidReq.ProtoReflect.Descriptor instead.
func (*GetOrdersByUidReq) Descriptor() ([]byte, []int) {
	return file_quant_order_proto_rawDescGZIP(), []int{6}
}

func (x *GetOrdersByUidReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type GetOrdersByUidRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Orders []*OrderInfo `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
}

func (x *GetOrdersByUidRes) Reset() {
	*x = GetOrdersByUidRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quant_order_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOrdersByUidRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrdersByUidRes) ProtoMessage() {}

func (x *GetOrdersByUidRes) ProtoReflect() protoreflect.Message {
	mi := &file_quant_order_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrdersByUidRes.ProtoReflect.Descriptor instead.
func (*GetOrdersByUidRes) Descriptor() ([]byte, []int) {
	return file_quant_order_proto_rawDescGZIP(), []int{7}
}

func (x *GetOrdersByUidRes) GetOrders() []*OrderInfo {
	if x != nil {
		return x.Orders
	}
	return nil
}

type OrderInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uid       int64       `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	BrokeType int32       `protobuf:"varint,3,opt,name=broke_type,json=brokeType,proto3" json:"broke_type,omitempty"`
	QuantType int32       `protobuf:"varint,4,opt,name=quant_type,json=quantType,proto3" json:"quant_type,omitempty"`
	AssetType int32       `protobuf:"varint,5,opt,name=asset_type,json=assetType,proto3" json:"asset_type,omitempty"`
	AssetCode string      `protobuf:"bytes,6,opt,name=asset_code,json=assetCode,proto3" json:"asset_code,omitempty"`
	Total     int64       `protobuf:"varint,7,opt,name=total,proto3" json:"total,omitempty"`
	Grids     []*GridData `protobuf:"bytes,8,rep,name=grids,proto3" json:"grids,omitempty"`
	Hold      int64       `protobuf:"varint,9,opt,name=hold,proto3" json:"hold,omitempty"`
	Profit    int64       `protobuf:"varint,10,opt,name=profit,proto3" json:"profit,omitempty"`
	Freeze    int64       `protobuf:"varint,11,opt,name=freeze,proto3" json:"freeze,omitempty"`
	Status    int32       `protobuf:"varint,12,opt,name=status,proto3" json:"status,omitempty"`
	Ct        int64       `protobuf:"varint,13,opt,name=ct,proto3" json:"ct,omitempty"`
}

func (x *OrderInfo) Reset() {
	*x = OrderInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quant_order_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderInfo) ProtoMessage() {}

func (x *OrderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_quant_order_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderInfo.ProtoReflect.Descriptor instead.
func (*OrderInfo) Descriptor() ([]byte, []int) {
	return file_quant_order_proto_rawDescGZIP(), []int{8}
}

func (x *OrderInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderInfo) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *OrderInfo) GetBrokeType() int32 {
	if x != nil {
		return x.BrokeType
	}
	return 0
}

func (x *OrderInfo) GetQuantType() int32 {
	if x != nil {
		return x.QuantType
	}
	return 0
}

func (x *OrderInfo) GetAssetType() int32 {
	if x != nil {
		return x.AssetType
	}
	return 0
}

func (x *OrderInfo) GetAssetCode() string {
	if x != nil {
		return x.AssetCode
	}
	return ""
}

func (x *OrderInfo) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *OrderInfo) GetGrids() []*GridData {
	if x != nil {
		return x.Grids
	}
	return nil
}

func (x *OrderInfo) GetHold() int64 {
	if x != nil {
		return x.Hold
	}
	return 0
}

func (x *OrderInfo) GetProfit() int64 {
	if x != nil {
		return x.Profit
	}
	return 0
}

func (x *OrderInfo) GetFreeze() int64 {
	if x != nil {
		return x.Freeze
	}
	return 0
}

func (x *OrderInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *OrderInfo) GetCt() int64 {
	if x != nil {
		return x.Ct
	}
	return 0
}

type GetGridTrialReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid int64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	// 券商类型 1模拟交易
	BrokerType int32 `protobuf:"varint,2,opt,name=broker_type,json=brokerType,proto3" json:"broker_type,omitempty"`
	// 量化类型 1网格交易
	QuantType int32 `protobuf:"varint,3,opt,name=quant_type,json=quantType,proto3" json:"quant_type,omitempty"`
	// 资产类型 1上证 2深证 3美股(包括道琼斯和纳斯达克) 4港股
	AssetType int32 `protobuf:"varint,4,opt,name=asset_type,json=assetType,proto3" json:"asset_type,omitempty"`
	// 资产代号
	AssetCode string `protobuf:"bytes,5,opt,name=asset_code,json=assetCode,proto3" json:"asset_code,omitempty"`
	// 投入资金量 全都*1000,转为整数
	TotalMoney int64 `protobuf:"varint,6,opt,name=total_money,json=totalMoney,proto3" json:"total_money,omitempty"`
	// 网格数量
	GridNum int64 `protobuf:"varint,7,opt,name=grid_num,json=gridNum,proto3" json:"grid_num,omitempty"`
	// 网格上限
	GridMax int64 `protobuf:"varint,8,opt,name=grid_max,json=gridMax,proto3" json:"grid_max,omitempty"`
	// 网格下限
	GridMin int64 `protobuf:"varint,9,opt,name=grid_min,json=gridMin,proto3" json:"grid_min,omitempty"`
}

func (x *GetGridTrialReq) Reset() {
	*x = GetGridTrialReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quant_order_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGridTrialReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGridTrialReq) ProtoMessage() {}

func (x *GetGridTrialReq) ProtoReflect() protoreflect.Message {
	mi := &file_quant_order_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGridTrialReq.ProtoReflect.Descriptor instead.
func (*GetGridTrialReq) Descriptor() ([]byte, []int) {
	return file_quant_order_proto_rawDescGZIP(), []int{9}
}

func (x *GetGridTrialReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *GetGridTrialReq) GetBrokerType() int32 {
	if x != nil {
		return x.BrokerType
	}
	return 0
}

func (x *GetGridTrialReq) GetQuantType() int32 {
	if x != nil {
		return x.QuantType
	}
	return 0
}

func (x *GetGridTrialReq) GetAssetType() int32 {
	if x != nil {
		return x.AssetType
	}
	return 0
}

func (x *GetGridTrialReq) GetAssetCode() string {
	if x != nil {
		return x.AssetCode
	}
	return ""
}

func (x *GetGridTrialReq) GetTotalMoney() int64 {
	if x != nil {
		return x.TotalMoney
	}
	return 0
}

func (x *GetGridTrialReq) GetGridNum() int64 {
	if x != nil {
		return x.GridNum
	}
	return 0
}

func (x *GetGridTrialReq) GetGridMax() int64 {
	if x != nil {
		return x.GridMax
	}
	return 0
}

func (x *GetGridTrialReq) GetGridMin() int64 {
	if x != nil {
		return x.GridMin
	}
	return 0
}

type GetGridTrialRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 投入资金量
	TotalMoney int64 `protobuf:"varint,1,opt,name=total_money,json=totalMoney,proto3" json:"total_money,omitempty"`
	// 网格详情
	Grids []*GridData `protobuf:"bytes,2,rep,name=grids,proto3" json:"grids,omitempty"`
}

func (x *GetGridTrialRes) Reset() {
	*x = GetGridTrialRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quant_order_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGridTrialRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGridTrialRes) ProtoMessage() {}

func (x *GetGridTrialRes) ProtoReflect() protoreflect.Message {
	mi := &file_quant_order_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGridTrialRes.ProtoReflect.Descriptor instead.
func (*GetGridTrialRes) Descriptor() ([]byte, []int) {
	return file_quant_order_proto_rawDescGZIP(), []int{10}
}

func (x *GetGridTrialRes) GetTotalMoney() int64 {
	if x != nil {
		return x.TotalMoney
	}
	return 0
}

func (x *GetGridTrialRes) GetGrids() []*GridData {
	if x != nil {
		return x.Grids
	}
	return nil
}

var File_quant_order_proto protoreflect.FileDescriptor

var file_quant_order_proto_rawDesc = []byte{
	0x0a, 0x11, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x2d, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x03, 0x70, 0x75, 0x62, 0x22, 0x96, 0x02, 0x0a, 0x12, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x47, 0x72, 0x69, 0x64, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12,
	0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69,
	0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x73, 0x73, 0x65, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x61, 0x73, 0x73, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x73, 0x73, 0x65, 0x74, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x73, 0x73, 0x65, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x1f, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x4d, 0x6f, 0x6e, 0x65, 0x79,
	0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x69, 0x64, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x07, 0x67, 0x72, 0x69, 0x64, 0x4e, 0x75, 0x6d, 0x12, 0x19, 0x0a, 0x08, 0x67,
	0x72, 0x69, 0x64, 0x5f, 0x6d, 0x61, 0x78, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x67,
	0x72, 0x69, 0x64, 0x4d, 0x61, 0x78, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x69, 0x64, 0x5f, 0x6d,
	0x69, 0x6e, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x67, 0x72, 0x69, 0x64, 0x4d, 0x69,
	0x6e, 0x22, 0x5a, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x72, 0x69, 0x64, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x5f, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x12, 0x23, 0x0a, 0x05, 0x67, 0x72, 0x69, 0x64,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x75, 0x62, 0x2e, 0x47, 0x72,
	0x69, 0x64, 0x44, 0x61, 0x74, 0x61, 0x52, 0x05, 0x67, 0x72, 0x69, 0x64, 0x73, 0x22, 0x5d, 0x0a,
	0x08, 0x47, 0x72, 0x69, 0x64, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x73, 0x73,
	0x65, 0x74, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x61, 0x73,
	0x73, 0x65, 0x74, 0x4e, 0x75, 0x6d, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x69, 0x64, 0x5f, 0x6d,
	0x61, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x67, 0x72, 0x69, 0x64, 0x4d, 0x61,
	0x78, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x69, 0x64, 0x5f, 0x6d, 0x69, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x07, 0x67, 0x72, 0x69, 0x64, 0x4d, 0x69, 0x6e, 0x22, 0x62, 0x0a, 0x05,
	0x41, 0x73, 0x73, 0x65, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x73, 0x73, 0x65, 0x74, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x61, 0x73, 0x73, 0x65, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x73, 0x73, 0x65, 0x74, 0x5f, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x73, 0x73, 0x65, 0x74, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x73, 0x73, 0x65, 0x74, 0x5f, 0x6e, 0x75, 0x6d,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x61, 0x73, 0x73, 0x65, 0x74, 0x4e, 0x75, 0x6d,
	0x22, 0x33, 0x0a, 0x0d, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03,
	0x75, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x03, 0x6f, 0x69, 0x64, 0x22, 0x0f, 0x0a, 0x0d, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x22, 0x25, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x73, 0x42, 0x79, 0x55, 0x69, 0x64, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0x3b, 0x0a,
	0x11, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x42, 0x79, 0x55, 0x69, 0x64, 0x52,
	0x65, 0x73, 0x12, 0x26, 0x0a, 0x06, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x75, 0x62, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x06, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x22, 0xd0, 0x02, 0x0a, 0x09, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x72,
	0x6f, 0x6b, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09,
	0x62, 0x72, 0x6f, 0x6b, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x71, 0x75, 0x61,
	0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x71,
	0x75, 0x61, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x73, 0x73, 0x65,
	0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x61, 0x73,
	0x73, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x73, 0x73, 0x65, 0x74,
	0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x73, 0x73,
	0x65, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x23, 0x0a, 0x05,
	0x67, 0x72, 0x69, 0x64, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x75,
	0x62, 0x2e, 0x47, 0x72, 0x69, 0x64, 0x44, 0x61, 0x74, 0x61, 0x52, 0x05, 0x67, 0x72, 0x69, 0x64,
	0x73, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x6c, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x04, 0x68, 0x6f, 0x6c, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x74, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x66, 0x72, 0x65, 0x65, 0x7a, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x66,
	0x72, 0x65, 0x65, 0x7a, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x0c, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0e, 0x0a,
	0x02, 0x63, 0x74, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x63, 0x74, 0x22, 0x93, 0x02,
	0x0a, 0x0f, 0x47, 0x65, 0x74, 0x47, 0x72, 0x69, 0x64, 0x54, 0x72, 0x69, 0x61, 0x6c, 0x52, 0x65,
	0x71, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03,
	0x75, 0x69, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x73, 0x73, 0x65, 0x74, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x61, 0x73, 0x73, 0x65, 0x74, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x73, 0x73, 0x65, 0x74, 0x5f, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x73, 0x73, 0x65, 0x74, 0x43, 0x6f, 0x64,
	0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x6d, 0x6f, 0x6e, 0x65, 0x79,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x4d, 0x6f, 0x6e,
	0x65, 0x79, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x69, 0x64, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x67, 0x72, 0x69, 0x64, 0x4e, 0x75, 0x6d, 0x12, 0x19, 0x0a,
	0x08, 0x67, 0x72, 0x69, 0x64, 0x5f, 0x6d, 0x61, 0x78, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x07, 0x67, 0x72, 0x69, 0x64, 0x4d, 0x61, 0x78, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x69, 0x64,
	0x5f, 0x6d, 0x69, 0x6e, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x67, 0x72, 0x69, 0x64,
	0x4d, 0x69, 0x6e, 0x22, 0x57, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x47, 0x72, 0x69, 0x64, 0x54, 0x72,
	0x69, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f,
	0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x12, 0x23, 0x0a, 0x05, 0x67, 0x72, 0x69, 0x64, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x75, 0x62, 0x2e, 0x47, 0x72, 0x69,
	0x64, 0x44, 0x61, 0x74, 0x61, 0x52, 0x05, 0x67, 0x72, 0x69, 0x64, 0x73, 0x32, 0x8e, 0x02, 0x0a,
	0x05, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x45, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x47, 0x72, 0x69, 0x64, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x17, 0x2e, 0x70, 0x75, 0x62, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x72, 0x69, 0x64, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x1a, 0x17, 0x2e, 0x70, 0x75, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47,
	0x72, 0x69, 0x64, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x36, 0x0a,
	0x0a, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x12, 0x2e, 0x70, 0x75,
	0x62, 0x2e, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a,
	0x12, 0x2e, 0x70, 0x75, 0x62, 0x2e, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x42, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x73, 0x42, 0x79, 0x55, 0x69, 0x64, 0x12, 0x16, 0x2e, 0x70, 0x75, 0x62, 0x2e, 0x47, 0x65,
	0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x42, 0x79, 0x55, 0x69, 0x64, 0x52, 0x65, 0x71, 0x1a,
	0x16, 0x2e, 0x70, 0x75, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x42,
	0x79, 0x55, 0x69, 0x64, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x42, 0x0a, 0x0c, 0x47, 0x65, 0x74,
	0x47, 0x72, 0x69, 0x64, 0x54, 0x72, 0x69, 0x61, 0x6c, 0x12, 0x17, 0x2e, 0x70, 0x75, 0x62, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x72, 0x69, 0x64, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x1a, 0x17, 0x2e, 0x70, 0x75, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47,
	0x72, 0x69, 0x64, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x22, 0x00, 0x42, 0x2b, 0x5a,
	0x29, 0x2f, 0x55, 0x73, 0x65, 0x72, 0x73, 0x2f, 0x77, 0x65, 0x69, 0x77, 0x65, 0x6e, 0x63, 0x68,
	0x6f, 0x6e, 0x67, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2f, 0x71, 0x75, 0x61, 0x6e, 0x74,
	0x2d, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2f, 0x70, 0x75, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_quant_order_proto_rawDescOnce sync.Once
	file_quant_order_proto_rawDescData = file_quant_order_proto_rawDesc
)

func file_quant_order_proto_rawDescGZIP() []byte {
	file_quant_order_proto_rawDescOnce.Do(func() {
		file_quant_order_proto_rawDescData = protoimpl.X.CompressGZIP(file_quant_order_proto_rawDescData)
	})
	return file_quant_order_proto_rawDescData
}

var file_quant_order_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_quant_order_proto_goTypes = []interface{}{
	(*CreateGridOrderReq)(nil), // 0: pub.CreateGridOrderReq
	(*CreateGridOrderRes)(nil), // 1: pub.CreateGridOrderRes
	(*GridData)(nil),           // 2: pub.GridData
	(*Asset)(nil),              // 3: pub.Asset
	(*CloseOrderReq)(nil),      // 4: pub.CloseOrderReq
	(*CloseOrderRes)(nil),      // 5: pub.CloseOrderRes
	(*GetOrdersByUidReq)(nil),  // 6: pub.GetOrdersByUidReq
	(*GetOrdersByUidRes)(nil),  // 7: pub.GetOrdersByUidRes
	(*OrderInfo)(nil),          // 8: pub.OrderInfo
	(*GetGridTrialReq)(nil),    // 9: pub.GetGridTrialReq
	(*GetGridTrialRes)(nil),    // 10: pub.GetGridTrialRes
}
var file_quant_order_proto_depIdxs = []int32{
	2, // 0: pub.CreateGridOrderRes.grids:type_name -> pub.GridData
	8, // 1: pub.GetOrdersByUidRes.orders:type_name -> pub.OrderInfo
	2, // 2: pub.OrderInfo.grids:type_name -> pub.GridData
	2, // 3: pub.GetGridTrialRes.grids:type_name -> pub.GridData
	0, // 4: pub.Order.CreateGridOrder:input_type -> pub.CreateGridOrderReq
	4, // 5: pub.Order.CloseOrder:input_type -> pub.CloseOrderReq
	6, // 6: pub.Order.GetOrdersByUid:input_type -> pub.GetOrdersByUidReq
	0, // 7: pub.Order.GetGridTrial:input_type -> pub.CreateGridOrderReq
	1, // 8: pub.Order.CreateGridOrder:output_type -> pub.CreateGridOrderRes
	5, // 9: pub.Order.CloseOrder:output_type -> pub.CloseOrderRes
	7, // 10: pub.Order.GetOrdersByUid:output_type -> pub.GetOrdersByUidRes
	1, // 11: pub.Order.GetGridTrial:output_type -> pub.CreateGridOrderRes
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_quant_order_proto_init() }
func file_quant_order_proto_init() {
	if File_quant_order_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_quant_order_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateGridOrderReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quant_order_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateGridOrderRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quant_order_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GridData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quant_order_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Asset); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quant_order_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CloseOrderReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quant_order_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CloseOrderRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quant_order_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOrdersByUidReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quant_order_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOrdersByUidRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quant_order_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quant_order_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGridTrialReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quant_order_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGridTrialRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_quant_order_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_quant_order_proto_goTypes,
		DependencyIndexes: file_quant_order_proto_depIdxs,
		MessageInfos:      file_quant_order_proto_msgTypes,
	}.Build()
	File_quant_order_proto = out.File
	file_quant_order_proto_rawDesc = nil
	file_quant_order_proto_goTypes = nil
	file_quant_order_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// OrderClient is the client API for Order service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrderClient interface {
	// 创建订单
	CreateGridOrder(ctx context.Context, in *CreateGridOrderReq, opts ...grpc.CallOption) (*CreateGridOrderRes, error)
	// 关闭订单
	CloseOrder(ctx context.Context, in *CloseOrderReq, opts ...grpc.CallOption) (*CloseOrderRes, error)
	// 根据uid获取订单详情
	GetOrdersByUid(ctx context.Context, in *GetOrdersByUidReq, opts ...grpc.CallOption) (*GetOrdersByUidRes, error)
	// 网格试算
	GetGridTrial(ctx context.Context, in *CreateGridOrderReq, opts ...grpc.CallOption) (*CreateGridOrderRes, error)
}

type orderClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderClient(cc grpc.ClientConnInterface) OrderClient {
	return &orderClient{cc}
}

func (c *orderClient) CreateGridOrder(ctx context.Context, in *CreateGridOrderReq, opts ...grpc.CallOption) (*CreateGridOrderRes, error) {
	out := new(CreateGridOrderRes)
	err := c.cc.Invoke(ctx, "/pub.Order/CreateGridOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) CloseOrder(ctx context.Context, in *CloseOrderReq, opts ...grpc.CallOption) (*CloseOrderRes, error) {
	out := new(CloseOrderRes)
	err := c.cc.Invoke(ctx, "/pub.Order/CloseOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) GetOrdersByUid(ctx context.Context, in *GetOrdersByUidReq, opts ...grpc.CallOption) (*GetOrdersByUidRes, error) {
	out := new(GetOrdersByUidRes)
	err := c.cc.Invoke(ctx, "/pub.Order/GetOrdersByUid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) GetGridTrial(ctx context.Context, in *CreateGridOrderReq, opts ...grpc.CallOption) (*CreateGridOrderRes, error) {
	out := new(CreateGridOrderRes)
	err := c.cc.Invoke(ctx, "/pub.Order/GetGridTrial", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderServer is the server API for Order service.
type OrderServer interface {
	// 创建订单
	CreateGridOrder(context.Context, *CreateGridOrderReq) (*CreateGridOrderRes, error)
	// 关闭订单
	CloseOrder(context.Context, *CloseOrderReq) (*CloseOrderRes, error)
	// 根据uid获取订单详情
	GetOrdersByUid(context.Context, *GetOrdersByUidReq) (*GetOrdersByUidRes, error)
	// 网格试算
	GetGridTrial(context.Context, *CreateGridOrderReq) (*CreateGridOrderRes, error)
}

// UnimplementedOrderServer can be embedded to have forward compatible implementations.
type UnimplementedOrderServer struct {
}

func (*UnimplementedOrderServer) CreateGridOrder(context.Context, *CreateGridOrderReq) (*CreateGridOrderRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGridOrder not implemented")
}
func (*UnimplementedOrderServer) CloseOrder(context.Context, *CloseOrderReq) (*CloseOrderRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseOrder not implemented")
}
func (*UnimplementedOrderServer) GetOrdersByUid(context.Context, *GetOrdersByUidReq) (*GetOrdersByUidRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrdersByUid not implemented")
}
func (*UnimplementedOrderServer) GetGridTrial(context.Context, *CreateGridOrderReq) (*CreateGridOrderRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGridTrial not implemented")
}

func RegisterOrderServer(s *grpc.Server, srv OrderServer) {
	s.RegisterService(&_Order_serviceDesc, srv)
}

func _Order_CreateGridOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGridOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).CreateGridOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pub.Order/CreateGridOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).CreateGridOrder(ctx, req.(*CreateGridOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_CloseOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).CloseOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pub.Order/CloseOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).CloseOrder(ctx, req.(*CloseOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_GetOrdersByUid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrdersByUidReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).GetOrdersByUid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pub.Order/GetOrdersByUid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).GetOrdersByUid(ctx, req.(*GetOrdersByUidReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_GetGridTrial_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGridOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).GetGridTrial(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pub.Order/GetGridTrial",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).GetGridTrial(ctx, req.(*CreateGridOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Order_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pub.Order",
	HandlerType: (*OrderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateGridOrder",
			Handler:    _Order_CreateGridOrder_Handler,
		},
		{
			MethodName: "CloseOrder",
			Handler:    _Order_CloseOrder_Handler,
		},
		{
			MethodName: "GetOrdersByUid",
			Handler:    _Order_GetOrdersByUid_Handler,
		},
		{
			MethodName: "GetGridTrial",
			Handler:    _Order_GetGridTrial_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "quant-order.proto",
}
